DELETE http://localhost:3003/api/blogs/64ef8368e842b4c5112f3077
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0ZWYyOGM1MjNlNjZmMzI5ZDNhNWY5NSIsImlhdCI6MTY5MzQxODE4NSwiZXhwIjoxNjkzNDIxNzg1fQ.De68LORok7KkRaWNqDOrZlHQWDKPyGybJ92MAqhqDPk
